#!/usr/bin/env bash
# This script tells a story based on each line of /etc/passwd
while IFS=: read -r user x uid gid gecos home shell
do
echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $x, more info about the user here: $gecos"
done < /etc/passwd
