#!/usr/bin/env bash
# This script writes its PID to a file and handles SIGTERM, SIGINT, SIGQUIT
echo $$ > /var/run/myscript.pid

cleanup () {
echo "I hate the kill command"
rm -f /var/run/myscript.pid
exit 0
}

trap cleanup SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

while true
do
echo "To infinity and beyond"
sleep 2
done
